name: frc-ml
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.20.0
  - opencv>=4.5.0
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - open3d>=0.17.0  # For 3D point cloud visualization
  - pip
  - pip:
    - ultralytics>=8.0.0  # For YOLOv8
    - timm>=0.6.7
    - einops>=0.6.0
    - pynetworktables>=2021.0.0  # For NetworkTables communication with RoboRIO
    - midas>=1.0.0  # MiDaS for fallback depth estimation